### ISSUE TITLE
Upgrade to latest FlicpClock JS (0.7.4)

### ISSUE THREAD

**Issue by knightq** [TrevorS/flipclockjs-rails#1]
It would be useful to:
- Upgrade to the latest version of the JS library
- Make it clear which version of the JS library this gem refers to

**Comment by TrevorS** [comment]
Resolved by #2.

**Comment by knightq** [comment]
Thank you!
Please, release also the gem on rubygems ASAP!

**Comment by TrevorS** [comment]
Updated to 0.7.7 and released.

https://github.com/objectivehtml/FlipClock/releases/tag/0.7.7
